repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        language_version: python3
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format
